config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :profile # get /profile
      resources :users

      get 'user/events', to: 'volunteer_applications#index', as: 'api_v1_user_events'

      resources :events do
        collection do
          get 'featured', to: 'events#featured', as: 'api_v1_events_featured'
        end
      end

      post 'events/:event_id/actions/apply', to: 'volunteer_applications#create', as: 'api_v1_apply'
    end
  end

  resources :events do
    resources :volunteer_applications do
      put 'confirm'
      put 'pending'
      put 'decline'
    end
  end
  resources :dashboard, only: [:index]
  resource :profile, only: [:show, :edit, :update]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, raise: false
  def index
    @events = current_user.events
  end
end

app/views/dashboard/index.html.erb
<div class="dashboard-container">
  <h3>我的活动</h3>
  <div class="dashbaord-events">

    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-4">
          <%= link_to event_path(event), class: 'panel__dashboard-event-link' do %>
            <div class="panel panel__dashboard-event">
              <div class="panel-body">
                <div class="event-poster">
                  <%= image_tag event.poster || 'http://placehold.it/200x200' %>
                </div>

                <hr/>

                <div class="event-name">
                  <%= event.title %>
                </div>
                <div class="event-date">
                  <i class="fa fa-calendar"></i>
                  <%= event.date %>
                </div>
                <div class="event-location">
                  <i class="fa fa-map-marker"></i>
                  <%= event.location %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="col-md-4">
        <%= link_to new_event_url do %>
          <div class="panel panel__dashboard-event panel__dashboard--event-new">
            <div class="panel-body">
              <div>
                <%= image_tag "create-icon.png", class: "icon-new" %>
              </div>
              <div class="info">
                <div style="color: #2DB94D;">创建新活动</div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>