config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :profile # get /profile
      resources :users

      get 'user/events', to: 'volunteer_applications#index', as: 'api_v1_user_events'

      resources :events do
        collection do
          get 'featured', to: 'events#featured', as: 'api_v1_events_featured'
        end
      end

      post 'events/:event_id/actions/apply', to: 'volunteer_applications#create', as: 'api_v1_apply'
    end
  end

  resources :events do
    resources :volunteer_applications do
      put 'confirm'
      put 'pending'
      put 'decline'
    end
  end
  resources :dashboard, only: [:index]
  resource :profile, only: [:show, :edit, :update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= raw notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "squarelogo.png", class: "logo" %>
        有志者 VolunteerUs
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <%= image_tag gravatar_url(current_user.email, 64), alt: "", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle"=> "dropdown", style: "border-radius: 40px;" %>
            <ul class="dropdown-menu">
              <li>
                <%= link_to profile_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "个人资料") %>
                <% end %>
              </li>
              <li>
                <%= link_to dashboard_index_path do %>
                  <i class="fa fa-compass"></i>  <%= t(".profile", default: "我的活动") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "退出") %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= link_to t(".sign_in", default: "注册 | 登录"), new_user_session_path, class: "btn btn-success", style: "margin-top: 5px" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>