config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :profile # get /profile
      resources :users

      get 'user/events', to: 'volunteer_applications#index', as: 'api_v1_user_events'

      resources :events do
        collection do
          get 'featured', to: 'events#featured', as: 'api_v1_events_featured'
        end
      end

      post 'events/:event_id/actions/apply', to: 'volunteer_applications#create', as: 'api_v1_apply'
    end
  end

  resources :events do
    resources :volunteer_applications do
      put 'confirm'
      put 'pending'
      put 'decline'
    end
  end
  resources :dashboard, only: [:index]
  resource :profile, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord

  CATEGORY_MAP = [
    {
      id: "startup",
      name: "科技创业"
    },
    {
      id: "healthcare",
      name: "健康医疗"
    },
    {
      id: "education",
      name: "教育"
    },
    {
      id: "sports",
      name: "运动健身"
    },
    {
      id: "sharing event",
      name: "交流会"
    },
    {
      id: "cars",
      name: "汽车"
    },
    {
      id: "home and lifestyle",
      name: "时尚生活"
    },
    {
      id: "career",
      name: "职场"
    }
  ]
  CATEGORY_IDS = CATEGORY_MAP.map { |category_item| category_item[:name] }

  belongs_to :user
  has_many :volunteer_applications, dependent: :destroy
  validates :title, :location, :volunteer_number, :poster, :description, :volunteer_duties, :volunteer_perks, presence: true
  validates :category, inclusion: { in: CATEGORY_IDS }
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController
  # respond_to :json
  acts_as_token_authentication_handler_for User

  # before_action :set_user, only: [ :show ]

  # after_action :verify_authorized, except: [:index, :create]

  def index

    puts "index"
    puts "Event #{Event.all.inspect}"
    render :ok, json: Event.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])

    if application = VolunteerApplication.find_by(user: current_user, event: @event)
      render :ok, json: application
    else
      render :ok, json: @event
    end
  end

  def featured
    render :ok, json: Event.where(featured: true)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  #this shows the list of volunteers for an event
  # def index
  #   @events = Event.all
  # end


  def show
    @event = Event.find(params[:id])

    @qr_code_file_path = "assets/event-qrcode-#{@event.id}.png"

    unless File.exists?(Rails.root.join('public', @qr_code_file_path))
      access_token = GetAccessToken.call
      GenerateQRCode.call(access_token, @event.id)
    end

    @volunteer_applications = @event.volunteer_applications
  end

  def new
    if current_user
      @event = Event.new
    else
      redirect_to new_user_registration_path
    end
    # @event.title ||= params[:title]
  end

  #this create a new event
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    # Check to see if the user is registered/logged in
    if current_user.nil?
     # Store the form data in the session so we can retrieve it after login
     Thread.current[:event_params] = event_params.dup
     p Thread.current[:event_params]

     # Redirect the user to register/login
     redirect_to new_user_registration_path
    else
      if @event.save

        puts "save @event #{@event.errors.inspect}"

        redirect_to event_path(@event), notice: '<i class="fa fa-weixin"></i> 扫活动生成二维码，分享到朋友圈招募志愿者'
      else

        puts "failed @event #{@event.errors.inspect}"

        render :new
      end
    end
  end

  #show the edit form
  def edit
     @event = Event.find(params[:id])
  end

  #submit the edit form
  def update
    @event = Event.find(params[:id])
    @event.user = current_user
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end

  end

  # #this one can be seen by other people
  # def publish
  # end

  # #you can delete the event
  # def unpublish
  # end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to dashboard_index_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    # These params are required to create an event in event/new view
    result = params.require(:event).permit(:title, :date, :poster, :location, :category, :volunteer_number, :volunteer_perks, :volunteer_duties, :featured, :description)

    result[:category] = Event::CATEGORY_MAP.find { |i| i[:id] == result[:category] }[:name]

    result
  end

end

app/helpers/event_helper.rb
module EventHelper
  def event_categories_for_select
    Event::CATEGORY_MAP.map { |category_item| [category_item[:name], category_item[:id]] }
  end
end

app/views/events/edit.html.erb
<%= render "layouts/event-form" %>

app/views/events/new.html.erb
<%= render "layouts/event-form" %>

app/views/events/show.html.erb
<div class="container tab-space">
  <div class="main-content-container">
    <div>

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">志愿者状态</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">活动内容</a></li>
        <li role="presentation"><a href="#qr-code" aria-controls="qr-code" role="tab" data-toggle="tab">活动二维码</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
          <table class="table">
            <thead>
              <tr>
                <th>
                 申请时间
                </th>
                <th>
                 志愿者姓名
                </th>
                <th>
                 申请状态
                </th>
                <th>
                 待审核
                </th>
                <th>
                 手机号码
                </th>
                <th>
                 邮箱
                </th>
              </tr>
            </thead>

            <tbody>
              <% @volunteer_applications.each do |volunteer_application| %>
                <tr>
                  <td>
                    <%= volunteer_application.created_at.strftime("%b %d %I:%M%P") %>
                  </td>
                  <td>
                    <%= volunteer_application.name %>
                  </td>
                  <td>
                    <%= volunteer_application.status.humanize %>
                  </td>
                  <td>
                    <% if volunteer_application.may_accept? %>
                      <%= link_to "Confirm", event_volunteer_application_confirm_path(event_id: @event.id, volunteer_application_id: volunteer_application.id), method: :put, class: 'btn btn-success' %>
                    <% end %>
                    <% if volunteer_application.may_decline? %>
                      <%= link_to "Decline", event_volunteer_application_decline_path(event_id: @event.id, volunteer_application_id: volunteer_application.id), method: :put, class: 'btn btn-danger' %>
                    <% end %>
                  </td>
                   <td>
                    <%= volunteer_application.phone_number %>
                  </td>
                   <td>
                    <%= volunteer_application.email.humanize %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if @volunteer_applications.empty? %>
            <div class="volunteer-default">
              <div class="modal fade" id="modal-event-show-qr-code">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h3 class="modal-title">在微信上分享下面的二维码吧</h3>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="event__qr-code">
                        <img src="/<%= @qr_code_file_path %>">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <h4 class="no-volunteers-note">你目前还没有志愿者哦</h4>
          <% end %>




        </div>

        <div role="tabpanel" class="tab-pane fade" id="profile">
          <h1><%= @event.title %></h1>
          <div class="row">
            <div class="col-md-6">
              <div class="event-poster">
                <%= image_tag @event.poster  %>
              </div>
            </div>

            <div class="col-md-6">
              <div class="event-basic">
                <p><span class="event-basic-label">活动时间</span>: <%= @event.date %></p>
                <p><span class="event-basic-label">活动地点</span>: <%= @event.location %></p>

                <!-- CSS needed in the event show page -->
                <p><span class="event-basic-label">活动种类</span>: <%= @event.category.capitalize %></p>
                <p><span class="event-basic-label">志愿者人数</span>: <%= @event.volunteer_number %></p>
                <p><span class="event-basic-label">组织者</span>: <%= @event.user.try(:name) %></p>
              </div>
            </div>
          </div>


          <div class="row">
            <div class="col-md-12">
              <div class="event-details">
                <p><span class="event-basic-label">活动详细内容</span>: <%= @event.description %></p>
                <p><span class="event-basic-label">志愿者义务</span>: <%= @event.volunteer_duties %></p>
                <p><span class="event-basic-label">志愿者福利</span>: <%= @event.volunteer_perks %></p>
              </div>

              <div class="action-buttons">
                <%= link_to "更新", edit_event_path(@event), class: 'btn btn-default' %>
                <%= link_to "删除", event_path(@event), class: 'btn btn-danger', method: "delete" %>
              </div>
            </div>
          </div>

        </div>

        <div role="tabpanel" class="tab-pane fade in" id="qr-code">
          <div class="event__qr-code">
             <img src="/<%= @qr_code_file_path %>">
          </div>
        </div>
      </div>
    </div>

    <div class="text-center back-button">
      <%= link_to "返回个人页面", dashboard_index_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

<% content_for(:inline_javascript) do %>
  <script>
    $('#modal-event-show-qr-code').modal({});
  </script>
<% end %>